# Numpy

In [3]:
# NumPy is a Python package for scientific computing, particularly for numerical operations on large arrays and matrices.
# pip install numpy # For installation
# Syntax : pip install <package_name>  ==>used to install a package from the Python Package Index (PyPI) or other package repositories.
# pip: package manager for Python that allows users to install and manage software packages written in Python.

In [4]:
import numpy as np
# import            numpy             as   np   
# keyword     library/modules name        alias 

# Array

In [14]:
# An array is a data structure that stores values of same data type (homogeneous).
# List store elements of different data type

# We can create NumPy arrays by converting a list/Tuple to an array.

# NumPy operations are faster than standard Python lists.

# we cannot apply mathematical operators directly on lists. element-wise operations with lists require a bunch of code
# we can apply mathematical operators directly on Array

In [16]:
#create array
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [17]:
type(a)

numpy.ndarray

In [18]:
len(a)

5

In [19]:
List=list(range(1,11))
List

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [20]:
type(List)

list

In [21]:
# create array using list
a1=np.array(List)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# typecasting
t=tuple(List)
t

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

In [24]:
type(t)

tuple

In [25]:
a2=np.array(t)
a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
# we cannot apply mathematical operators directly on lists. element-wise operations with lists require a bunch of code
# we can apply mathematical operators directly on Array

In [27]:
L+2 # This operation does not add . 2 list will be concat

NameError: name 'L' is not defined

In [28]:
print(a)

[1 2 3 4 5]


In [29]:
print(a+2)

[3 4 5 6 7]


In [30]:
List+List

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [35]:
# element-wise operations with lists require a bunch of code
# 1) Using for loop
list1=[]
for i in List:
    # print(i+2, end=" ,")
    list1.append(i+2)

list1

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [36]:
List*2  # multiplyer should be int for rep

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [37]:
a*2 # multiplies each array element with 2

array([ 2,  4,  6,  8, 10])

In [38]:
List*1.9


TypeError: can't multiply sequence by non-int of type 'float'

In [39]:
a*1.9

array([1.9, 3.8, 5.7, 7.6, 9.5])

In [40]:
# List store elements of different data type (Mixed datatype)
# Array store elements of same data type (homogeneous)

In [41]:
l1=[1,2,'mansi','python']
l1

[1, 2, 'mansi', 'python']

In [42]:
arr=np.array([1,2,'mansi','python'])
arr

array(['1', '2', 'mansi', 'python'], dtype='<U21')

In [ ]:
type(arr)

numpy.ndarray

In [44]:
type(l1[0])

int

In [45]:
type(l1[2])

str

In [46]:
type(arr[0])

numpy.str_

In [47]:
type(arr[2])

numpy.str_

In [48]:
np.array([1,2,3,4,5],dtype='str')

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [49]:
np.array([0.1,0.3,3.5,6.4],dtype='int')

array([0, 0, 3, 6])

In [50]:
np.array([1,2,3,4,5,6],dtype=float)

array([1., 2., 3., 4., 5., 6.])