### Manipulate Arrays

In [1]:
import numpy as np

In [2]:
# np.append(): adds values to the end of an array. It returns a new array
# np.concatenate(): Combines two or more arrays along a specified axis
# np.vstack(): Stacks arrays vertically (row-wise)
# np.hstack(): Stacks arrays horizontally (column-wise)
#  "stack" refers to the operation of joining multiple arrays along a new axis

#row axis=0
#col axis=1

In [3]:
#append
a=np.arange(1,16).reshape(3,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [6]:
b=np.arange(16,31).reshape(3,5)
b

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [7]:
np.append(a,b)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [9]:
arr=np.append(a,b,axis=0)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [10]:
arr1=np.append(a,b,axis=1)
arr1

array([[ 1,  2,  3,  4,  5, 16, 17, 18, 19, 20],
       [ 6,  7,  8,  9, 10, 21, 22, 23, 24, 25],
       [11, 12, 13, 14, 15, 26, 27, 28, 29, 30]])

In [11]:
# combining
# concatenate
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
b

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [14]:
np.concatenate((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [15]:
np.concatenate((a,b),axis=1)

array([[ 1,  2,  3,  4,  5, 16, 17, 18, 19, 20],
       [ 6,  7,  8,  9, 10, 21, 22, 23, 24, 25],
       [11, 12, 13, 14, 15, 26, 27, 28, 29, 30]])

In [16]:
np.concatenate((a,b,a),axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [17]:
# vstack

In [19]:
np.vstack((a,b,a))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [20]:
np.vstack((a,b,c),axis=1)

NameError: name 'c' is not defined

In [21]:
np.hstack((a,b))

array([[ 1,  2,  3,  4,  5, 16, 17, 18, 19, 20],
       [ 6,  7,  8,  9, 10, 21, 22, 23, 24, 25],
       [11, 12, 13, 14, 15, 26, 27, 28, 29, 30]])

In [22]:
np.column_stack((a,b))

array([[ 1,  2,  3,  4,  5, 16, 17, 18, 19, 20],
       [ 6,  7,  8,  9, 10, 21, 22, 23, 24, 25],
       [11, 12, 13, 14, 15, 26, 27, 28, 29, 30]])

In [23]:
np.row_stack((a,b))

C:\Users\hi\AppData\Local\Temp\ipykernel_34268\1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [24]:
np.r_[a,b]   # row added

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [25]:
np.c_[a,b]  # columns are added

array([[ 1,  2,  3,  4,  5, 16, 17, 18, 19, 20],
       [ 6,  7,  8,  9, 10, 21, 22, 23, 24, 25],
       [11, 12, 13, 14, 15, 26, 27, 28, 29, 30]])

### Spliting

In [27]:
p=np.arange(1,31).reshape(6,5)
p

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [28]:
np.vsplit(p,3)

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]),
 array([[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]])]

In [29]:
np.split(p,2)

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]])]

In [30]:
np.hsplit(p,3)

ValueError: array split does not result in an equal division

In [31]:
np.hsplit(p,5)

[array([[ 1],
        [ 6],
        [11],
        [16],
        [21],
        [26]]),
 array([[ 2],
        [ 7],
        [12],
        [17],
        [22],
        [27]]),
 array([[ 3],
        [ 8],
        [13],
        [18],
        [23],
        [28]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24],
        [29]]),
 array([[ 5],
        [10],
        [15],
        [20],
        [25],
        [30]])]

In [32]:
a1,a2,a3=np.vsplit(p,3)

In [33]:
a1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [34]:
a2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [35]:
a3

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [36]:
h1,h2,h3,h4,h5=np.hsplit(p,5)

In [37]:
h1

array([[ 1],
       [ 6],
       [11],
       [16],
       [21],
       [26]])

In [38]:
h2

array([[ 2],
       [ 7],
       [12],
       [17],
       [22],
       [27]])

In [39]:
h3

array([[ 3],
       [ 8],
       [13],
       [18],
       [23],
       [28]])

In [40]:
h4

array([[ 4],
       [ 9],
       [14],
       [19],
       [24],
       [29]])

In [41]:
h5

array([[ 5],
       [10],
       [15],
       [20],
       [25],
       [30]])

### Masking / Boolean Indexing or Boolean Masking

In [42]:
# Masking is a technique used in programming and data processing to select, hide, or modify data based on a condition.
# A mask is a boolean array (True/False) that controls which values are kept, removed, or changed.

In [43]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [45]:
arr[arr>5]

array([6, 7, 8, 9])

In [47]:
arr[~(arr>5)]

array([0, 1, 2, 3, 4, 5])