In [1]:
import numpy as np

# Create array using np.arange() function
- Returns an array with evenly spaced elements as per the step size(by default 1)
- It has the following paramaters:
  * start : start of interval range. By default start = 0
  * stop  : end of interval range
  * step  : step size of interval. By default step size = 1
- Fractional step count is allowed in arange. Fractional stepsize not allowed in range.

In [2]:
# Syntax: 
#  np.arange(start,      end,    stepsize,   dtype)
#           optional            optional   optional
#              0                   +1
                               # fractional step count is allowed 

In [3]:
l1=list(range(10))
l1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
l2=tuple(range(10))
l2

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

In [7]:
l3=list(range(1,11,2))
l3

[1, 3, 5, 7, 9]

In [9]:
l4=list(range(1,11,2.5))
print(l4)

TypeError: 'float' object cannot be interpreted as an integer

In [10]:
# now let do it this with arange
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [13]:
np.arange(1,11,2.5)

array([1. , 3.5, 6. , 8.5])

In [14]:
np.arange(2,10,2,float)


array([2., 4., 6., 8.])

In [15]:
np.arange(2,10,2,str)

TypeError: arange() not supported for inputs with DType <class 'numpy.dtypes.StrDType'>.

In [16]:
np.arange(dtype=int,step=2, stop=20, start=10)

array([10, 12, 14, 16, 18])

#  Create array Using np.linspace() function
- Returns evenly spaced numbers over a specified interval. Here the start and stop both are included.            
- It has the following parameters:              
    - start: start of interval range. By default start = 0
    - stop: end of interval range
    - num : No. of samples to generate. By default num = 50

In [17]:
#Syntax :- 
#np.linspace(start, stop,  num,    endpoint=True,    retstep=False)
#                         (part)   include/exclud    Gives stepsize
#                        optional    optional        optional
#                          50          True            False

In [22]:
a=np.linspace(1,10)
a

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [23]:
len(a)

50

In [26]:
c=np.linspace(1,10,10)

In [27]:
c

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [28]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [29]:
np.linspace(1,10,5,retstep=True)

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), np.float64(2.25))

In [30]:
c=np.linspace(1,10,10,retstep=True)

In [31]:
c

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), np.float64(1.0))

In [32]:
np.linspace(1,20,10,endpoint=False)

array([ 1. ,  2.9,  4.8,  6.7,  8.6, 10.5, 12.4, 14.3, 16.2, 18.1])