In [3]:
import numpy as np

In [4]:
# Creating 1D array: Excel (perticular column only)
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [5]:
# Creating  2D array: Excel sheet (similar not exact) (Row and columns)

arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
type(arr2d)

numpy.ndarray

In [7]:
# Creating  3D array: Image

arr3d = np.array([[[1, 2, 3], [4, 5, 6]]])
arr3d

array([[[1, 2, 3],
        [4, 5, 6]]])

In [11]:
arr3d.shape  #(Frame, row, column)

(1, 2, 3)

In [12]:
arr2d.shape

(2, 3)

In [13]:
arr3d

array([[[1, 2, 3],
        [4, 5, 6]]])

In [14]:
# Reshape : Change shape of array
# M1
# Array.reshape(shape,Fill_by)
# shape= (row,col)
# Fill_by "C" ===> Fill_by Row
#         "F" ===> Fill_by column

# M2
# np.reshape(data,shape,order(Fill_by))
# shape= (row,col)
# order (Fill_by) "C" ===> Fill_by Row
#         "F" ===> Fill_by column


In [19]:
p=np.arange(1,13)
p

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [20]:
p.ndim

1

In [21]:
p.shape

(12,)

In [22]:
q=p.reshape(3,4)
q

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
q=p.reshape(4,3)
q

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [24]:
# Array.reshape(shape,Fill_by)
# shape= (row,col)
# Fill_by "C" ===> Fill_by Row
#         "F" ===> Fill_by column

In [26]:
p.reshape((4,3),order="C") # Need to define parameter name "order"

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [27]:
p.reshape((4,3),order="F")

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [28]:
np.reshape(p,(4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [29]:
# M2
# np.reshape(data,shape,order(Fill_by))
# shape= (row,col)
# order (Fill_by) "C" ===> Fill_by Row
#         "F" ===> Fill_by column

In [30]:
# How define shape

In [32]:
np.reshape(p,(4,2),"F")  # If values is less than new shape we got error

ValueError: cannot reshape array of size 12 into shape (4,2)

In [33]:
c=np.arange(27)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [35]:
np.reshape(c,(9,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [36]:
np.reshape(c,(9,3),order="F")

array([[ 0,  9, 18],
       [ 1, 10, 19],
       [ 2, 11, 20],
       [ 3, 12, 21],
       [ 4, 13, 22],
       [ 5, 14, 23],
       [ 6, 15, 24],
       [ 7, 16, 25],
       [ 8, 17, 26]])

In [37]:
np.reshape(c,(3,9),order="F")

array([[ 0,  3,  6,  9, 12, 15, 18, 21, 24],
       [ 1,  4,  7, 10, 13, 16, 19, 22, 25],
       [ 2,  5,  8, 11, 14, 17, 20, 23, 26]])

In [39]:
a1=np.reshape(c,(1,3,9),order="F")
a1

array([[[ 0,  3,  6,  9, 12, 15, 18, 21, 24],
        [ 1,  4,  7, 10, 13, 16, 19, 22, 25],
        [ 2,  5,  8, 11, 14, 17, 20, 23, 26]]])

In [40]:
a1.ndim

3

In [41]:
a2=np.reshape(c,(3,3,3),order="F")
a2

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [42]:
a2.ndim

3

In [43]:
np.reshape(c,(9,3),"F")

array([[ 0,  9, 18],
       [ 1, 10, 19],
       [ 2, 11, 20],
       [ 3, 12, 21],
       [ 4, 13, 22],
       [ 5, 14, 23],
       [ 6, 15, 24],
       [ 7, 16, 25],
       [ 8, 17, 26]])

In [44]:
np.reshape(c,(3,3,3),"F")

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])