In [1]:
import numpy as np

### around()

In [2]:
round(34.634235,3)

34.634

In [3]:
a = np.array([23.355,45.456456,34.65778787,44.7878])

In [5]:
np.around(a,decimals=2)#evenly round all elements to the given number of decimals.

array([23.36, 45.46, 34.66, 44.79])

In [41]:
np.round(a,2)

array([23.36, 45.46, 34.66, 44.79])

### Matrix operations

In [8]:
# Element-wise operations:
# Addition: np.add()
# Subtraction: np.subtract()
# Division: np.divide()
# Multiplication: np.multiply()

In [12]:
# Define two matrices to multiply
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 7]])

In [13]:
m1

array([[1, 2],
       [3, 4]])

In [14]:
m2

array([[5, 6],
       [7, 7]])

In [15]:
np.add(m1,m2)

array([[ 6,  8],
       [10, 11]])

In [16]:
np.subtract(m1,m2)

array([[-4, -4],
       [-4, -3]])

In [17]:
np.divide(m1,m2)

array([[0.2       , 0.33333333],
       [0.42857143, 0.57142857]])

In [18]:
m1+m2

array([[ 6,  8],
       [10, 11]])

In [19]:
m1-m2

array([[-4, -4],
       [-4, -3]])

In [20]:
m1/m2

array([[0.2       , 0.33333333],
       [0.42857143, 0.57142857]])

In [21]:
m1*m2

array([[ 5, 12],
       [21, 28]])

In [23]:
np.multiply(m1,m2)

array([[ 5, 12],
       [21, 28]])

### Linear Algebra

In [24]:
# np.dot(): Computes the dot product of two arrays. 
# np.linalg.inv(): Computes the inverse of a matrix.
# np.linalg.det(): Computes the determinant of a matrix.
# np.linalg.eig(): Computes the eigenvalues and right eigenvectors of a square array.

In [25]:
m1

array([[1, 2],
       [3, 4]])

In [26]:
m2

array([[5, 6],
       [7, 7]])

In [27]:
np.dot(m1,m2)

array([[19, 20],
       [43, 46]])

In [28]:
# another way to get the dot product
res=m1@m2

In [29]:
res

array([[19, 20],
       [43, 46]])

In [30]:
#determinant

In [34]:
m1

array([[1, 2],
       [3, 4]])

In [40]:
det=np.linalg.det(m1)
round(det,3)

np.float64(-2.0)

In [36]:
m2

array([[5, 6],
       [7, 7]])

In [38]:
np.linalg.inv(m2)

array([[-1.        ,  0.85714286],
       [ 1.        , -0.71428571]])

In [42]:
matrix=m2

In [43]:
matrix

array([[5, 6],
       [7, 7]])

In [44]:
# calculate the eigenvalues

In [45]:
np.linalg.eig(matrix)

EigResult(eigenvalues=array([-0.55743852, 12.55743852]), eigenvectors=array([[-0.73364588, -0.62178711],
       [ 0.67953198, -0.78318631]]))